image: node:10

stages:
  - setup
  - build
  - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules

# Setup Stage
setup:
    stage: setup
    script:
        - npm ci
    only:
        - master
        - merge_requests

# Build Stage
build:website:
    stage: build
    artifacts:
        name: "build-website-{$CI_COMMIT_REF_SLUG}-{$CI_COMMIT_SHORT_SHA}"
        paths:
            - dist
    script:
        - npm run build:prod
    only:
        - master
        - merge_requests

# Deploy Stage
deploy:production:
    stage: deploy
    environment:
        name: production
    only:
        - master
    script:
        - echo "Deploy to Production"
